#############################################################################
# Makefile for building: LUServer_Full
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  LUServer_Full.pro
# Template: subdirs
# Command: C:\Qt\5.7\msvc2015_64\bin\qmake.exe -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile LUServer_Full.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.7\msvc2015_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro \
		sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro \
		sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro


sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-qmake_all:  FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ exit 1
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ && $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\QtRakNet.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ && $(MAKE) -f Makefile qmake_all
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro: FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\QtRakNet.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-make_first: FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\QtRakNet.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-all: FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\QtRakNet.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-clean: FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\QtRakNet.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-distclean: FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\QtRakNet.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-install_subtargets: FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\QtRakNet.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-uninstall_subtargets: FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\QtRakNet.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-qmake_all: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-qmake_all sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-qmake_all FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ exit 1
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ && $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\LUServer.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile.LUServer
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ && $(MAKE) -f Makefile.LUServer qmake_all
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro \
		sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ && ( if not exist Makefile.LUServer $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\LUServer.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile.LUServer ) && $(MAKE) -f Makefile.LUServer
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-make_first: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-make_first sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-make_first FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ && ( if not exist Makefile.LUServer $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\LUServer.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile.LUServer ) && $(MAKE) -f Makefile.LUServer 
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-all: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-all sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-all FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ && ( if not exist Makefile.LUServer $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\LUServer.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile.LUServer ) && $(MAKE) -f Makefile.LUServer all
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-clean: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-clean sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-clean FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ && ( if not exist Makefile.LUServer $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\LUServer.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile.LUServer ) && $(MAKE) -f Makefile.LUServer clean
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-distclean: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-distclean sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-distclean FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ && ( if not exist Makefile.LUServer $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\LUServer.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile.LUServer ) && $(MAKE) -f Makefile.LUServer distclean
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-install_subtargets: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-install_subtargets sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-install_subtargets FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ && ( if not exist Makefile.LUServer $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\LUServer.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile.LUServer ) && $(MAKE) -f Makefile.LUServer install
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-uninstall_subtargets: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-uninstall_subtargets sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-uninstall_subtargets FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ && ( if not exist Makefile.LUServer $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\LUServer.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile.LUServer ) && $(MAKE) -f Makefile.LUServer uninstall
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-qmake_all:  FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ exit 1
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ && $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ConsoleThread.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ && $(MAKE) -f Makefile qmake_all
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro: FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ConsoleThread.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-make_first: FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ConsoleThread.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-all: FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ConsoleThread.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-clean: FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ConsoleThread.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-distclean: FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ConsoleThread.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-install_subtargets: FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ConsoleThread.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-uninstall_subtargets: FORCE
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ConsoleThread.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: LUServer_Full.pro C:\Qt\5.7\msvc2015_64\mkspecs\win32-msvc2015\qmake.conf C:\Qt\5.7\msvc2015_64\mkspecs\features\spec_pre.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\common\angle.conf \
		C:\Qt\5.7\msvc2015_64\mkspecs\common\msvc-base.conf \
		C:\Qt\5.7\msvc2015_64\mkspecs\common\msvc-desktop.conf \
		C:\Qt\5.7\msvc2015_64\mkspecs\qconfig.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dextras.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3drender.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axbase.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axserver.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_clucene_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_dbus.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_gamepad.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_location.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_location_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_platformsupport_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_script.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_script_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_scripttools.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_scxml.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webengine.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webengine_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginecore.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_winextras.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\qt_functions.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\qt_config.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\qt_config.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\win32-msvc2015\qmake.conf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\spec_post.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\exclusive_builds.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\toolchain.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\default_pre.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\default_pre.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\resolve_config.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\default_post.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\qml_debug.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\rtti.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\precompile_header.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\warn_on.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\file_copies.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\windows.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\testcase_targets.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\exceptions.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\yacc.prf \
		C:\Qt\5.7\msvc2015_64\mkspecs\features\lex.prf \
		LUServer_Full.pro
	$(QMAKE) -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile LUServer_Full.pro
C:\Qt\5.7\msvc2015_64\mkspecs\features\spec_pre.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\common\angle.conf:
C:\Qt\5.7\msvc2015_64\mkspecs\common\msvc-base.conf:
C:\Qt\5.7\msvc2015_64\mkspecs\common\msvc-desktop.conf:
C:\Qt\5.7\msvc2015_64\mkspecs\qconfig.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dextras.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquick.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3drender.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_clucene_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_core.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_dbus.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_dbus_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_gamepad.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_help.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_location.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_network.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_script.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_script_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_scxml.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_scxml_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webengine.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webengine_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginecore.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Qt\5.7\msvc2015_64\mkspecs\features\qt_functions.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\qt_config.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\qt_config.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\win32-msvc2015\qmake.conf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\spec_post.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\exclusive_builds.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\toolchain.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\default_pre.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\default_pre.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\resolve_config.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\default_post.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\qml_debug.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\rtti.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\precompile_header.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\warn_on.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\file_copies.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\win32\windows.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\testcase_targets.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\exceptions.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\yacc.prf:
C:\Qt\5.7\msvc2015_64\mkspecs\features\lex.prf:
LUServer_Full.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile LUServer_Full.pro

qmake_all: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-qmake_all sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-qmake_all sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-qmake_all FORCE

make_first: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-make_first sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-make_first sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-make_first  FORCE
all: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-all sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-all sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-all  FORCE
clean: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-clean sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-clean sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-clean  FORCE
distclean: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-distclean sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-distclean sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-distclean  FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-install_subtargets sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-install_subtargets sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-install_subtargets FORCE
uninstall_subtargets: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-uninstall_subtargets sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-uninstall_subtargets sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-uninstall_subtargets FORCE

sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-debug:
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\QtRakNet.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-debug: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-debug sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-debug
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ && ( if not exist Makefile.LUServer $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\LUServer.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile.LUServer ) && $(MAKE) -f Makefile.LUServer debug
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-debug:
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ConsoleThread.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-debug sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-debug sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-debug

sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-release:
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\QtRakNet.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-release: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-release sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-release
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ && ( if not exist Makefile.LUServer $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\LUServer.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile.LUServer ) && $(MAKE) -f Makefile.LUServer release
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-release:
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ConsoleThread.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
release: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-release sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-release sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-release

sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-check:
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\QtRakNet.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-check: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-check sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-check
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ && ( if not exist Makefile.LUServer $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\LUServer.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile.LUServer ) && $(MAKE) -f Makefile.LUServer check
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-check:
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ConsoleThread.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
check: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-check sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-check sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-check

sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-benchmark:
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\QtRakNet.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-benchmark: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-benchmark sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-benchmark
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\ && ( if not exist Makefile.LUServer $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\LUServer.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile.LUServer ) && $(MAKE) -f Makefile.LUServer benchmark
sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-benchmark:
	@if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ mkdir C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ & if not exist C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ && ( if not exist Makefile $(QMAKE) C:\Users\Andrew_Stelter\Documents\Code\Side-Projects\NexusQt\QtRakNet\ConsoleThread\ConsoleThread.pro -spec win32-msvc2015 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
benchmark: sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-QtRakNet-pro-benchmark sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-LUServer-pro-benchmark sub-C--Users-Andrew_Stelter-Documents-Code-Side-Projects-NexusQt-QtRakNet-ConsoleThread-ConsoleThread-pro-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

